---
title: "Guia 2--Permutacion y Combinacion"
author: "Pablo Hurtado Salinas"
date: "2025-09-12"
output: html_document
---
Permutación----
En permutación importa el orden de los elementos y la formula se puede representar de la siguente manera.

$_{n}P_{r}= \frac{n!}{(n-r)!}$

Combinación----
En combinacion no importa el orden de los elementos para realizar los calculos y se puede representar de la siguente manera.

combinations enumera las posibles combinaciones de un tamaño especifico sobre los elementos de un vector. 

$_{n}C_{r} = \frac{n!}{(n-r)! r!}$



```{r}
#Funcion permutacion en R----
Permutaciones_sin<- function(n,r){
  return(factorial(n)/factorial(n-r))
}
Permutaciones_repe<- function(n,r){
  return(n^r)
}

#Función de Combinación en R----
Combinacion<- function(n,r){
  return(factorial(n)/factorial(n-r),factorial(n))
}

Combinacion_repe <- function(n,r){
  return (factorial(n + r - 1)) / (factorial(r) * factorial(n - 1))
}

#EJERCICIO 4A-----

permu_a =gtools::permutations(11,3)
print(nrow(permu_a))

Permutaciones_repeticion = gtools::permutations(11,3,repeats=TRUE)
print(nrow(Permutaciones_repeticion))
#EJERCICIO 4B-----

Combinacion_letra_sinrepe= nrow(gtools::combinations(5,3,letters[1:5],repeats.allowed = FALSE))
print(Combinacion_letra_sinrepe)

Combinacion_letra_repe= nrow(gtools::combinations(5,3,letters[1:5],repeats.allowed = TRUE))
print(Combinacion_letra_repe)

#EJERCICIO 4C-----

#Permutación
Permutaciones_sin(39,35)
print(Permutaciones_sin)

#Combinacion
Combinacion_repe(39,25)
print(nrow(Combinacion_repe))

```
Considere un problema de una vendedora viajera que debe recorrer 50 ciudades y volver al origen
 sin pasar dos veces por la misma ciudad. Considerando que solo existe una ruta óptima, si se
 selecciona una ruta al azar
 
 a) (10 puntos) ¿cuál es la probabilidad de que sea la ruta óptima?
 b) (10 puntos) Si se selecciona una ruta al azar que es distinta a la anterior ¿cuál es la
 probabilidad de que sea la ruta óptima?

Desarrollo: El caso de la viajera es una situacion de permutacion sin repeticion, ya que se presenta una restriccion de no repetir ciudad.

````{R}
##Establecemos el valor de n como una constante para este caso.

n= 50 #Representación de las 50 ciudades

total_rutas = factorial(n-1)

rutas_optimas= 1/total_rutas


format(total_rutas,scientific=TRUE)
format(rutas_optimas,scientific=TRUE)

cat("El total de rutas es: ",total_rutas,"\n")
cat("La las rutas optimas: ", rutas_optimas,"\n")





````

(10 puntos) De un grupo de 40 personas se quiere saber la opinión de 3 personas (seleccionadas al
azar) acerca del apruebo o rechazo de la nueva constitución. Si se sabe que 22 personas aprueban
y 18 rechazan ¿cuál es la probabilidad de que las dos personas seleccionadas rechacen?


Desarrollo: Nos fijamos que es el caso de una Hipergeometrica donde tenemos que realizar las combinaciones manualmente sin repeticion.

````{R}
# --- Cálculo (sin dhyper) ---
N <- 40    # tamaño población
K <- 18    # número de rechazantes en la poblacion (éxitos)
n <- 2     # tamaño de la muestra
k <- 2     # queremos exactamente k = 2 rechazantes

# combinatorios intermedios
comb_K_k <- choose(K, k)           # C(18,2)
comb_rest <- choose(N - K, n - k)  # C(22,0)
comb_total <- choose(N, n)         # C(40,2)

# probabilidad hipergeométrica manual
prob_manual <- (comb_K_k * comb_rest) / comb_total


cat("C(18,2) =", comb_K_k, "\n")
cat("C(22,0) =", comb_rest, "\n")
cat("C(40,2) =", comb_total, "\n")
cat("Probabilidad (manual) =", prob_manual, "\n")

````